- name: Create user nur
  become: true
  become_method: sudo
  tasks:
    - name: Add user nur
      ansible.builtin.user:
        name: nur
        comment: "This is nur"
        group: root
    - name: create dir
      ansible.builtin.file:
        path: /home/nur
        state: directory
    - name: create dir
      ansible.builtin.file:
        path: /home/nur/test
        state: directory

